service: alexa-skill-service

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "*"
          Resource:
            - arn:aws:iot:us-east-1:538326754995:*
custom:
  skillId: amzn1.ask.skill.9e1f5657-5d8c-493b-a5d7-563c0c4a8129

functions:
  esp32AlexaSkillFunction:
    handler: index.handler
    events:
      - alexaSmartHome: ${self:custom.skillId}